version: "3.9"

networks:
  flat-renting-network:
      driver: bridge

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flat-rental
    networks:
      - flat-renting-network
  web-api:
    image: falcon64/flat-renting-api:0.6
    depends_on: 
      - "db"
    ports:
      - 8080:8080
    networks:
      - flat-renting-network
